<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>异步编程</title>
</head>
<body>
	<button>按钮</button>
	<div></div>
</body>
<script>
	var btn = document.querySelector('button');
	var div = document.querySelector('div');
	btn.onclick = function(){
		// 同步操作
		alert('hello');//耗时，用户不确定，任务不继续
	}

	// 异步
	// let i = 0;
	// setInterval(() => {
	// 	div.innerHTML = i++;
	// },100);//设置这个值不是准确是，会延后。会在主线程任务执行完才去执行

	// callback hell 回调地狱
	// setInterval(() => {
	// 	console.log(1);
	// 	setInterval(() => {
	// 		console.log(2);
	// 		setInterval(() => {
	// 			console.log(3);
	// 		},1000);
	// 	},1000);
	// },1000);


	/*解决异步编程问题*/
		/*
			Promise
				构造函数
				接受一个参数：callback，我们把要执行的异步任务放置在这个callback
				Promise对象内部会维护一个状态  
				--默认是：pending状态
				--成功：resolved
				--失败：rejected
		*/

	let p1 = new Promise( (resolve,reject) => {
		// 当Promise被实例化的时候，callback中的异步任务就会被执行

		// 我们可以通过出入resolve，reject去改变当前promise任务的状态
		// resolve,reject是两个函数，调用resolve这个函数，会把转改改成resolved，调用reject会把状态改成rejected
		setTimeout( () => {
			console.log(1);
			// resolve();
			reject();
		},1000)
	})

	console.log(p1);

	// then会接收两个参数，这个参数都是回调，当对应的promise对象的状态变成了resolved，那吗then的第一个callback就会被执行，如果变成了rejected，那么then的第二个callback就会被执行
	// then之后还会返回一个promise对象，默认的还走resolved，如果走失败可以手动改，return Promise.reject()
	// catch和then也会返回一个默认的resolved状态的promise对象
	let p2 = p1.then(() => {
		console.log('success');
	},() => {
		console.log('fail');
	});

	p1.then(() => {
		console.log(2);
	},() => {
		console.log('a');
		return Promise.reject();
	}).then(() => {
		console.log(3);
	}).then(() => {
		console.log(4);
	}).catch(err => {
		// catch和then也会返回一个默认的resolved状态的promise对象
		console.log('err');
	}).then(() => {
		console.log(5);
	})


</script>
</html>